package hospital.management.system.telas;

import hospital.management.system.entidades.Ambulatorio;
import hospital.management.system.entidades.Enfermeiro;
import hospital.management.system.entidades.Leito;
import hospital.management.system.persistencia.AmbulatorioDAO;
import hospital.management.system.persistencia.EnfermeiroDAO;
import hospital.management.system.persistencia.LeitoDAO;
import hospital.management.system.utils.DAOFactory;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class JPanelEnfermeiro extends javax.swing.JPanel {
    private EnfermeiroDAO enfermeiroDAO = DAOFactory.createEnfermeiroDAO();
    private LeitoDAO leitoDAO = DAOFactory.createLeitoDAO();
    private AmbulatorioDAO ambulatorioDAO = DAOFactory.createAmbulatorioDAO();

    public JPanelEnfermeiro() {
        initComponents();
        carregarTabelaEnfermeiro();
        carregarTabelaLeito();
        carregarTabelaAmbulatorio();
    }

    public void carregarTabelaEnfermeiro() {
        List<Enfermeiro> enfermeiros = enfermeiroDAO.listar();
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableEnfermeiro.getModel();
        int qntLinhas = modeloTabela.getRowCount();
        
        
        for (int i = 0; i < qntLinhas; i++) {
            modeloTabela.removeRow(0);
        }
        
        for (Enfermeiro enfermeiro: enfermeiros) {
            Object[] linha = new Object[10];
            linha[0] = enfermeiro.getId();
            linha[1] = enfermeiro.getNome();
            linha[2] = enfermeiro.getFuncao();
            linha[3] = enfermeiro.getCpf();
            linha[4] = enfermeiro.getSalario();
            linha[5] = enfermeiro.getHorario();
            linha[6] = enfermeiro.getTelefone();
            linha[7] = enfermeiro.getHorarioPlantao();
            linha[8] = enfermeiro.getRegistro();
            linha[9] = enfermeiro.getIdLeito();
            
            modeloTabela.addRow(linha);
        }
    }
    
     public void carregarTabelaLeito() {
        List<Leito> leitos = leitoDAO.listar();
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableLeito.getModel();
        int qntLinhas = modeloTabela.getRowCount();
        
        
        for (int i = 0; i < qntLinhas; i++) {
            modeloTabela.removeRow(0);
        }
        
        for (Leito leito: leitos) {
            Object[] linha = new Object[2];
            linha[0] = leito.getId();
            linha[1] = leito.getNumero();
            
            modeloTabela.addRow(linha);
        }
    }
    
     public void carregarTabelaAmbulatorio() {
        List<Ambulatorio> ambulatorios = ambulatorioDAO.listar();
        DefaultTableModel modeloTabela = (DefaultTableModel) jTableAmbulatorio.getModel();
        int qntLinhas = modeloTabela.getRowCount();
        
        
        for (int i = 0; i < qntLinhas; i++) {
            modeloTabela.removeRow(0);
        }
        
        for (Ambulatorio ambulatorio: ambulatorios) {
            Object[] linha = new Object[2];
            linha[0] = ambulatorio.getId();
            linha[1] = ambulatorio.getNumero();
            
            modeloTabela.addRow(linha);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelFuncao = new javax.swing.JLabel();
        jTextFieldFuncao = new javax.swing.JTextField();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelCpf = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabelSalario = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jLabelHorario = new javax.swing.JLabel();
        jTextFieldHorario = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabelHorarioPlantao = new javax.swing.JLabel();
        jTextFieldHorarioPlantao = new javax.swing.JTextField();
        jLabelRegistro = new javax.swing.JLabel();
        jTextFieldRegistro = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEnfermeiro = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAmbulatorio = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLeito = new javax.swing.JTable();
        jLabelLeito = new javax.swing.JLabel();
        jLabelAmbulatorio = new javax.swing.JLabel();
        jLabelEnfermeiro = new javax.swing.JLabel();

        jLabelNome.setText("Nome:");

        jLabelFuncao.setText("Função:");

        jLabelId.setText("ID:");

        jTextFieldId.setEditable(false);

        jLabelCpf.setText("CPF:");

        jTextFieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCpfActionPerformed(evt);
            }
        });

        jLabelSalario.setText("Salário:");

        jLabelHorario.setText("Horário:");

        jLabelTelefone.setText("Telefone:");

        jLabelHorarioPlantao.setText("Horário do Plantão:");

        jTextFieldHorarioPlantao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHorarioPlantaoActionPerformed(evt);
            }
        });

        jLabelRegistro.setText("Registro:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar Campos");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableEnfermeiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Função", "CPF", "Salário", "Horário", "Telefone", "Horário do Plantão", "Registro", "idLeito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEnfermeiro);

        jTableAmbulatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Leito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAmbulatorio.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableAmbulatorio);
        if (jTableAmbulatorio.getColumnModel().getColumnCount() > 0) {
            jTableAmbulatorio.getColumnModel().getColumn(0).setResizable(false);
            jTableAmbulatorio.getColumnModel().getColumn(1).setResizable(false);
        }

        jTableLeito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Leito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLeito.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableLeito);
        if (jTableLeito.getColumnModel().getColumnCount() > 0) {
            jTableLeito.getColumnModel().getColumn(0).setResizable(false);
            jTableLeito.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabelLeito.setText("Leito");

        jLabelAmbulatorio.setText("Ambulatório");

        jLabelEnfermeiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEnfermeiro.setText("Enfermeiros");
        jLabelEnfermeiro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonExcluir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLeito)
                        .addGap(163, 163, 163)
                        .addComponent(jLabelAmbulatorio)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNome))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelFuncao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabelSalario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldSalario, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelCpf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCpf))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelHorario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTelefone))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelHorarioPlantao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldHorarioPlantao, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelRegistro)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldRegistro)
                                    .addComponent(jTextFieldTelefone))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jButtonSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(jLabelEnfermeiro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEnfermeiro)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelId)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelLeito)
                        .addComponent(jLabelAmbulatorio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelNome)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCpf))
                            .addComponent(jTextFieldCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelSalario)
                                .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelFuncao)
                                .addComponent(jTextFieldFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHorarioPlantao)
                            .addComponent(jTextFieldHorarioPlantao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRegistro)
                            .addComponent(jTextFieldRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHorario)
                            .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefone)
                            .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEditar)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonExcluir)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCpfActionPerformed

    }//GEN-LAST:event_jTextFieldCpfActionPerformed

    private void jTextFieldHorarioPlantaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHorarioPlantaoActionPerformed

    }//GEN-LAST:event_jTextFieldHorarioPlantaoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Enfermeiro enfermeiro = new Enfermeiro();
        int linhaL,linhaA;
        
        int id = 0;
        try {
        id = Integer.parseInt(jTextFieldId.getText());
        } catch(NumberFormatException ex) {
            id = 0;
        }
        enfermeiro.setId(id);
        enfermeiro.setNome(jTextFieldNome.getText());
        enfermeiro.setFuncao(jTextFieldFuncao.getText());
        enfermeiro.setCpf(jTextFieldCpf.getText());
        enfermeiro.setHorario(jTextFieldHorario.getText());
        enfermeiro.setSalario(Double.parseDouble(jTextFieldSalario.getText()));
        enfermeiro.setTelefone(jTextFieldTelefone.getText());
        enfermeiro.setHorarioPlantao(jTextFieldHorarioPlantao.getText());
        enfermeiro.setRegistro(Integer.parseInt(jTextFieldRegistro.getText()));
        
        linhaL = jTableLeito.getSelectedRow();
        if( linhaL!=-1){
          id = (int)jTableLeito.getValueAt(linhaL, 0);
          enfermeiro.setIdLeito(id);
        }
        
        linhaA = jTableAmbulatorio.getSelectedRow();
        if( linhaA!=-1){
          id = (int)jTableAmbulatorio.getValueAt(linhaA, 0);
          enfermeiro.setIdAmbulatorio(id);
        }
        
        if (enfermeiroDAO.getById(enfermeiro.getId()) == null) {
            enfermeiroDAO.inserir(enfermeiro);
        } else {
            enfermeiroDAO.editar(enfermeiro);
        }
        
        carregarTabelaEnfermeiro();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldId.setText("");
        jTextFieldNome.setText("");
        jTextFieldCpf.setText("");
        jTextFieldFuncao.setText("");
        jTextFieldSalario.setText("");
        jTextFieldHorario.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldHorarioPlantao.setText("");
        jTextFieldRegistro.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int linha = jTableEnfermeiro.getSelectedRow();

        if (linha >= 0) {
            int id =(int) jTableEnfermeiro.getValueAt(linha, 0);
            Enfermeiro enfermeiro = enfermeiroDAO.getById(id);
            
            jTextFieldId.setText( enfermeiro.getId()+ "");
            jTextFieldNome.setText(enfermeiro.getNome());
            jTextFieldFuncao.setText(enfermeiro.getFuncao());
            jTextFieldCpf.setText(enfermeiro.getCpf());
            jTextFieldSalario.setText(enfermeiro.getSalario()+ "");
            jTextFieldHorario.setText(enfermeiro.getHorario());
            jTextFieldTelefone.setText(enfermeiro.getTelefone());
            jTextFieldHorarioPlantao.setText(enfermeiro.getHorario());
            jTextFieldRegistro.setText(enfermeiro.getRegistro()+ "");
            
            for(int i=0;i<jTableLeito.getRowCount();i++){ 
                int idD = (int)jTableLeito.getValueAt(i, 0);
                if(enfermeiro.getIdLeito()==idD){
                    linha = i; 
                    break;
                }
            }
            jTableLeito.setRowSelectionInterval(linha, linha);
            
            for(int i=0;i<jTableAmbulatorio.getRowCount();i++){ 
                int idD = (int)jTableAmbulatorio.getValueAt(i, 0);
                if(enfermeiro.getIdAmbulatorio()==idD){
                    linha = i; 
                    break;
                }
            }
            jTableAmbulatorio.setRowSelectionInterval(linha, linha);
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int[] linhas = jTableEnfermeiro.getSelectedRows();
        for (int pos: linhas) {
            enfermeiroDAO.remover((int) jTableEnfermeiro.getValueAt(pos, 0));
        }
        carregarTabelaEnfermeiro();
    }//GEN-LAST:event_jButtonExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelAmbulatorio;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEnfermeiro;
    private javax.swing.JLabel jLabelFuncao;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelHorarioPlantao;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLeito;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAmbulatorio;
    private javax.swing.JTable jTableEnfermeiro;
    private javax.swing.JTable jTableLeito;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldFuncao;
    private javax.swing.JTextField jTextFieldHorario;
    private javax.swing.JTextField jTextFieldHorarioPlantao;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldRegistro;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
